# Generated by Django 5.1.4 on 2026-01-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('por_hacer', 'Por Hacer'), ('en_progreso', 'En Progreso'), ('revision', 'Revisión'), ('completado', 'Completado')], default='por_hacer', max_length=20),
        ),
    ]
