# Generated by Django 5.1.4 on 2026-01-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('activo', 'Activo'), ('completado', 'Completado'), ('archivado', 'Archivado'), ('en_pausa', 'En Pausa')], default='activo', max_length=20),
        ),
    ]
